#!/bin/bash
row_output(){
dig "$2.$1" |
grep -v -e "^$\|^;" |
awk '{split($1,domain,"."); print "The subdomain " domain[1] " is a " $4 " record and points to " $5}'
}

if [ -z "$2" ]
then
	SUBDOMAINS='www lb-01 web-01 web-02'
	for subdomain in $SUBDOMAINS; do
	row_output "$1" "$subdomain"
done
else
	row_output "$1" "$2"
fi
