#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect
sudo apt -y install nginx
sudo echo "Hello World" > index.html
sudo mv index.html /var/www/html/
sudo systemctl restart nginx
