#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect
sudo apt -y update
sudo apt -y install nginx
echo "Hello World" > index.html
sudo mv index.html /var/www/html/
sudo sed -i "/listen 80 default_server/a rewrite ^/redirect_me https://www.holbertonschool.com permanent;" /etc/nginx/sites-available/default
sudo service nginx restart

