#!/usr/bin/env bash
# script that configures a new Ubuntu machine to respect
sudo apt -y update
sudo apt -y install nginx
echo "Hello World" > index.html
sudo mv index.html /var/www/html/
echo "Ceci n'est pas une page" > 404.html
sudo mv my404error.html /var/www/html/
sudo sed -i "/listen 80 default_server;/ a error_page 404 /404.html;" /etc/nginx/sites-available/default
sudo service nginx restart

