#!/usr/bin/env bash
# script that generates a MySQL dump and
# creates a compressed archive out of it

DATE=`date +"%d-%m-%Y"`
mysqldump --opt --user=root --password=$1 tyrell_corp > backup.sql
tar -czvf ${DATE}.tar.gz backup.sql
