#!/usr/bin/env bash
# script that displays To infinity and beyond indefinitely
echo $$ > /var/run/myscript.pid
while :
do
	echo To infinity and beyond
	sleep 2
	trap "echo I hate the kill command" SIGTERM
	trap "echo Y U no love me?!" SIGINT
	trap 'rm -rf /var/run/holbertonscript.pid; exit' SIGQUIT
done
